import { Inter } from "next/font/google";
import '../styles/global.css';

const inter = Inter({ subsets: ["latin"] });

function MyApp({ Component, pageProps }) {
    return (
        <html lang="en">
        <head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
        </head>
        <body className={inter.className}>
        <Component {...pageProps} />
        </body>
        </html>
    );
}

export default MyApp;
